language: node_js
cache:
  directories:
  - node_modules
  - client/node_modules
deploy:
  provider: heroku
  api_key:
    secure: db80mOD7SouSMVlBgp0gOOFTnzyOT5HsmfUMAF+V7C3w9wsrQvCPCWWIt2fMbceeADqUfthJYaq8S5sWsYhP1Fzj0zC59uTxqNJLSu3YjafsGEZmt7tWqn6T/8fDrXLmVP21sFbisySNURf+rYgBGbwuxRAiVcy0uX1nM1fMXXlT2jmYTfO62+C13/XZew4JmBEqdFUu9SkRZrJ9yqR2uA67jyYlzyvgIRec1Fj8aajXoeBPMC0KtCcRpNmPSTLh8vcBxdIizKQmm9wywbsIPjX7vLw4FTc4cOHGgVkd7XYfPPBuzxQ89cxJgwrGXAC4iuT75T9D3xbn1onp4fzCdInpCYCf9ngqhhPrST6yMxVcCPybS8Onygg/vgHW0mMNKuyp7n/v5sN0ekPzOnZDQ7yzBrOam0SHJ9wM6Jbzw14DgZIuGk8SQmokBl14oARPD+IYZtQgCYlhTgYeCaenZyZ7QTBICji0WfyndjXEwuychE7yESToFBbbDHAajy6R1Dd75cnwthAjdgfovU4bfVxOpBfJFj9i+sX3doy2cNlSXtnKlHazl7lb4c8RmEbQDiieBnLa1aZ6uK0APc7tzOnjBLf9XbVhSKTcBJWwrMd2JPtv5VBreSjjhTI0sYQ8fpFwRUI9BaQ4ah2jxGtu7VIZJJoMSS4uC5FNd07mWa0=
  app: the-mern-shopping-list
  on:
    repo: above-the-line/mernShopper
